veins:
  diamond_ore: 1
  coal_ore: 3
  iron_ore: 2
  gold_ore: 1
  emerald_ore: 1
  lapis_ore: 2
  redstone_ore: 2
  copper_ore: 2

reset-count-inactivity-delay: 600 # 10 minutes

permission:
  command:
    revoke: "/lp user %player% permission set paper.antixray.bypass false"
    give: "/lp user %player% permission set paper.antixray.bypass true"

suspect-phase-time: 1200 # 20 minutes in ticks

refresh-chunks: true